name: Run Pre Flight Checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  pre-flight-checks:
    name: Pre Flight Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "v20.11.1"
      - name: Install and Setup Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          composer install
        shell: bash
      - name: Install VIP PHPCS
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer g require --dev automattic/vipwpcs -W
        shell: bash
      - name: Test VIP PHPCS
        run: |
          ls ~/.composer/vendor/bin
          phpcs --version
        shell: bash
      - name: Run VIP PHPCS
        run: |
          phpcs --standard=WordPress-VIP-Go -sp --basepath=. --ignore=vendor .
        shell: bash
